accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import signup

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('sign-up', signup, name='sign-up'),   
]

posts/urls.py
from django.urls import path

from .views import detail, create, like, likes, unlike

app_name = 'posts'
urlpatterns = [
    path('<int:pk>', detail, name='detail'),
    path('like/<int:pk>', like, name='like'), 
    path('unlike/<int:pk>', unlike, name='unlike'),    
    path('likes/<int:pk>', likes, name='likes'),
    path('create', create, name='create'),    
]

voofi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from accounts.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),    
    path('profile/<str:username>', profile, name='profile'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Post(models.Model):
    body = models.CharField(max_length=256)
    posted_at = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    reply = models.ForeignKey('posts.Post', null=True, on_delete=models.CASCADE, related_name='replies')
    likes = models.ManyToManyField(Like, related_name='post')

    def __str__(self):
        return f'{self.user.username}: {self.body[:50]}...'

    class Meta:
        ordering = ['-posted_at',]

posts/forms.py
from django.forms.models import ModelForm

from .models import Like, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('body',)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render


def profile(request, username):
    user = get_object_or_404(User, username=username)

    return render(request, 'accounts/profile.html', {'user': user})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/sign-up.html', {'form': form})

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from .models import Post, Like
from .forms import PostForm

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    return render(request, 'posts/detail.html', {'post': post})

@login_required
def create(request):
    if request.method == 'POST':
        # Deserialize your POST data
        form = PostForm(request.POST)
        model = form.save(commit=False)

        # Create an actual model
        model.user = request.user
        model.save()

        return redirect('posts:detail', pk=model.pk)

    elif request.method == 'GET':
        form = PostForm()
        return render(request, 'posts/create.html', {'form': form})

@login_required
def like(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if post.likes.filter(user=request.user).exists():
        return JsonResponse({ 'error': 'you already like this post'}, status=401)
    else:
        like = Like.objects.create(user=request.user)
        post.likes.add(like)
        post.save()

        return JsonResponse({ 'success': True })

@login_required
def unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    like = post.likes.filter(user=request.user)

    if like.exists():
        post.likes.remove(like.first())
        post.save()
        like.delete()
        return JsonResponse({ 'success': True })
    else:
        return JsonResponse({ 'error': 'you don\'t already like this post'}, status=401)
        

@login_required
def likes(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if post.likes.filter(user=request.user).exists():
        return JsonResponse({ 'success': True })
    else:
        return JsonResponse({ 'success': False })

templates/accounts/profile.html
{% extends 'layout.html' %}

{% block content %}
    <div id="profile">
        <h4>{{ user.username }}</h4>
        {% if request.user == user %}
            {% include 'posts/_create_form.html' %}
        {% endif %}
        <div>
            {% for post in user.posts.all %}
            <a href="{% url 'posts:detail' pk=post.pk %}">
                <div class="post">
                    {{ post.body }}
                    <div>
                        {{ post.user.username }}
                        {{ post.posted_at }}
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Voofi!</h1>
{% endblock content %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
    <link rel="stylesheet" href="{% static 'css/site.css' %}">    
</head>
<body>
    <nav>
        <div class="logo">
            <a href="{% url 'home' %}">Voofi</a>
        </div>
        
        {% if user.is_authenticated %}
        <div class="nav-item">
            <a href="{% url 'profile' username=user.username %}">Profile</a>            
        </div>
        <div class="nav-item">
            <a href="{% url 'accounts:logout' %}">Logout</a>            
        </div>
        {% else %}
        <div class="nav-item">
            <a href="{% url 'accounts:login' %}">Login</a>
        </div>
        <div class="nav-item">
            <a href="{% url 'accounts:sign-up' %}">Sign-Up</a>
        </div>
        {% endif %}
    </nav>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/posts/_create_form.html
<div>
    <form class="post-create-form" action="{% url 'posts:create' %}" method="POST">
        {% csrf_token %}
        <div>
            <textarea name="body" placeholder="Speak your mind!"></textarea>
        </div>
        <button>Post Your Mind</button>
    </form>
</div>

templates/posts/create.html
{% extends 'layout.html' %}

{% block content %}
    {% include 'posts/_create_form.html' %}
{% endblock content %}

templates/posts/detail.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div id="post">
        <blockquote>{{ post.body }}</blockquote>
        <div>
            <a href="{% url 'profile' username=post.user.username %}">
                {{ post.user.username }}
            </a>
            {{ post.posted_at }}
        </div>
        <div class="like-button" data-csrf="{{ csrf_token }}" data-pk="{{ post.pk }}">
            
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/site.js' %}"></script>
{% endblock scripts %}